# Generated by Django 5.2.4 on 2025-07-31 20:03

import django.db.models.deletion
import rbapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentClass",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=50)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="rbapp.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=rbapp.models.ledger_entry_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="rbapp.agency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=rbapp.models.customer_ledger_entry_upload_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_batch_id", models.IntegerField(blank=True, null=True)),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="N° compte bancaire",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "accounting_date",
                    models.DateField(help_text="Date comptabilisation"),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="N° document", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Description", max_length=255),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Montant débit",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Montant crédit",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "external_doc_number",
                    models.CharField(
                        blank=True,
                        help_text="N° doc. externe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Date d'échéance", null=True
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        help_text="Type de règlement",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Calculated amount (debit - credit)",
                        max_digits=20,
                    ),
                ),
                (
                    "customer_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="rbapp.customerledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "payment_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="rbapp.paymentclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("line", "payment_class")},
            },
        ),
        migrations.CreateModel(
            name="PaymentIdentification",
            fields=[
                ("line", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("debit", models.BooleanField(default=False)),
                ("credit", models.BooleanField(default=False)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_identifications",
                        to="rbapp.bank",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifications",
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_batch_id", models.IntegerField(blank=True, null=True)),
                ("operation_date", models.DateField()),
                ("label", models.CharField(max_length=255)),
                ("value_date", models.DateField()),
                ("debit", models.FloatField(blank=True, null=True)),
                ("credit", models.FloatField(blank=True, null=True)),
                (
                    "date_ref",
                    models.DateField(
                        blank=True,
                        help_text="Extracted date reference in YYYY-MM-DD format",
                        null=True,
                    ),
                ),
                ("ref", models.CharField(blank=True, max_length=255, null=True)),
                ("document_reference", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Transaction type classification",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bank_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="rbapp.bankledgerentry",
                    ),
                ),
                (
                    "payment_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rbapp.paymentclass",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bank",
            name="statuses",
            field=models.ManyToManyField(
                blank=True, related_name="banks", to="rbapp.paymentstatus"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="rbapp.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
