# Generated by Django 5.2.4 on 2025-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='document_number',
            field=models.CharField(blank=True, help_text='N° document', max_length=255, null=True),
        ),
    ] 