# Generated by Django 5.2.4 on 2025-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0005_add_document_number_to_customer_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertransaction",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total amount (absolute value)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
