# Generated by Django 5.2.4 on 2025-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0006_customertransaction_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="internal_number",
            field=models.CharField(
                blank=True,
                help_text="Internal reference number",
                max_length=255,
                null=True,
            ),
        ),
    ]
