# Generated by Django 5.2.4 on 2025-08-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0007_banktransaction_internal_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertransaction",
            name="matched_bank_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked bank transaction through internal_number",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_customer_transactions",
                to="rbapp.banktransaction",
            ),
        ),
    ]
