# Generated by Django 5.2.4 on 2025-08-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0008_customertransaction_matched_bank_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentidentification",
            name="grouped",
            field=models.BooleanField(default=False),
        ),
    ]
