# Generated by Django 5.2.4 on 2025-08-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0009_paymentidentification_grouped"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="rbapp.bank",
            ),
            preserve_default=False,
        ),
    ]
