# Generated by Django 5.2.4 on 2025-08-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0010_banktransaction_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formule_id", models.IntegerField()),
                (
                    "bank",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convention",
                        to="rbapp.bank",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions",
                        to="rbapp.company",
                    ),
                ),
                (
                    "payment_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions",
                        to="rbapp.paymentclass",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions",
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
    ]
