# Generated by Django 5.2.4 on 2025-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0011_convention"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgiosFormula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("formula", models.TextField(unique=True)),
            ],
        ),
    ]
