# Generated by Django 5.2.4 on 2025-08-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0012_agiosformula"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="rbapp.bank",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tax",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="rbapp.company",
            ),
            preserve_default=False,
        ),
    ]
