# Generated by Django 5.2.4 on 2025-08-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0013_tax_bank_tax_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertransaction",
            name="payment_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Status from matched bank transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_transactions",
                to="rbapp.paymentstatus",
            ),
        ),
    ]
