# Generated by Django 5.2.4 on 2025-08-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0014_customertransaction_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTaxRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("applied_formula", models.TextField(blank=True, null=True)),
                ("rate_used", models.FloatField(blank=True, null=True)),
                ("tmm_used", models.FloatField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rows",
                        to="rbapp.customertransaction",
                    ),
                ),
            ],
        ),
    ]
