# Generated by Django 5.2.4 on 2025-08-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0015_customertaxrow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="convention",
            unique_together={("company", "bank")},
        ),
        migrations.AddField(
            model_name="convention",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="name",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="convention",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rbapp.bank"
            ),
        ),
        migrations.AlterField(
            model_name="convention",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rbapp.company"
            ),
        ),
        migrations.RemoveField(
            model_name="convention",
            name="formule_id",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="payment_class",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="payment_status",
        ),
    ]
