# Generated by Django 5.2.4 on 2025-08-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0016_alter_convention_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_type", models.CharField(max_length=50)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("flat", "Flat Fee"),
                            ("formula", "Formula"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rate", models.FloatField(blank=True, null=True)),
                ("formula", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rules",
                        to="rbapp.convention",
                    ),
                ),
                (
                    "payment_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rbapp.paymentclass",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
    ]
