# Generated by Django 5.2.4 on 2025-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0017_taxrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
