# Generated by Django 5.2.4 on 2025-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0018_alter_convention_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="bank_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="convention",
            name="holidays",
            field=models.JSONField(
                default=list, help_text="List of ISO dates (e.g., ['2025-08-15'])"
            ),
        ),
        migrations.AddField(
            model_name="convention",
            name="tmm_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="Taux Moyen du Marché",
                max_digits=5,
            ),
            preserve_default=False,
        ),
    ]
