# Generated by Django 5.2.4 on 2025-08-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0019_convention_bank_days_convention_holidays_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="bank_days",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="holidays",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="tmm_rate",
        ),
        migrations.CreateModel(
            name="ConventionParameter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "value",
                    models.JSONField(
                        blank=True, default=list, help_text="List of strings or dates"
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="rbapp.convention",
                    ),
                ),
            ],
        ),
    ]
