# Generated by Django 5.2 on 2025-08-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0020_remove_convention_bank_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customertaxrow",
            name="tmm_used",
        ),
    ]
