# Generated by Django 5.2.4 on 2025-08-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0022_comparison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertaxrow",
            name="amount",
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
