# Generated by Django 5.2.4 on 2025-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0023_alter_customertaxrow_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="bank_tax",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="customer_tax",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
