# Generated by Django 5.2.4 on 2025-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0024_alter_comparison_bank_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionparameter",
            name="type",
            field=models.CharField(
                choices=[
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("str", "String"),
                    ("date", "Date"),
                    ("timedelta", "Timedelta"),
                ],
                default="str",
                help_text="Type of the parameter value",
                max_length=20,
            ),
        ),
    ]
