# Generated by Django 5.2.4 on 2025-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0025_conventionparameter_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgiosFormula",
        ),
        migrations.RemoveField(
            model_name="conventionparameter",
            name="type",
        ),
    ]
