# Generated by Django 5.2 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0026_delete_agiosformula_remove_conventionparameter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
