# Generated by Django 5.2.4 on 2025-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0027_comparison_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comparison",
            old_name="total_amount",
            new_name="customer_total_tax",
        ),
    ]
