# Generated by Django 5.2.4 on 2025-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0028_rename_total_amount_comparison_customer_total_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertaxrow",
            name="customer_total_tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Sum of customer tax for all transactions with the same document_number and tax type",
                max_digits=20,
                null=True,
            ),
        ),
    ]
