# Generated by Django 5.2.4 on 2025-08-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0029_customertaxrow_customer_total_tax"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customertaxrow",
            old_name="amount",
            new_name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="customertaxrow",
            name="customer_total_tax",
        ),
    ]
