# Generated by Django 5.2.4 on 2025-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0030_rename_amount_customertaxrow_tax_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertaxrow",
            name="total_tax_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total tax amount for all rows with the same document number",
                max_digits=20,
                null=True,
            ),
        ),
    ]
