# Generated by Django 5.2 on 2025-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0031_customertaxrow_total_tax_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="matched_bank_transaction_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the matched bank transaction for traceability",
                null=True,
            ),
        ),
    ]
