# Generated by Django 5.2.4 on 2025-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0032_comparison_matched_bank_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comparison",
            name="matched_bank_transaction_id",
        ),
        migrations.RemoveField(
            model_name="conventionparameter",
            name="convention",
        ),
        migrations.RemoveField(
            model_name="taxrule",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="customertaxrow",
            name="total_tax_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Sum of customer tax for all transactions with the same document_number and tax type",
                max_digits=20,
                null=True,
            ),
        ),
    ]
