# Generated by Django 5.2.4 on 2025-09-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0033_remove_comparison_matched_bank_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="matched_bank_transaction_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank transaction used for comparison",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rbapp.banktransaction",
            ),
        ),
    ]
