# Generated by Django 5.2.4 on 2025-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0034_comparison_matched_bank_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="matched_bank_transaction_id",
            field=models.IntegerField(
                blank=True,
                help_text="Bank transaction ID used for comparison",
                null=True,
            ),
        ),
    ]
