# Generated by Django 5.2.4 on 2025-09-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0035_alter_comparison_matched_bank_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="company",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="rbapp.company"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary company for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                to="rbapp.company",
            ),
        ),
    ]
