# Generated by Django 5.2.4 on 2025-09-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0036_remove_userprofile_company_userprofile_companies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerledgerentry",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_ledger_entries",
                to="rbapp.company",
                null=True,  # Allow null initially for existing records
                blank=True
            ),
        ),
    ]
