# Generated by Django 5.2.4 on 2025-09-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0038_add_company_field_to_customer_ledger_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerledgerentry",
            name="company",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="primary_company",
        ),
    ]
