# Generated by Django 5.2.4 on 2025-10-09 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0040_add_company_back_to_customer_ledger_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerledgerentry",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_ledger_entries",
                to="rbapp.company",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ReconciliationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_import_batch_id", models.IntegerField(blank=True, null=True)),
                (
                    "customer_import_batch_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_total", models.IntegerField(default=0)),
                ("progress_processed", models.IntegerField(default=0)),
                ("high_matches_count", models.IntegerField(default=0)),
                ("low_matches_count", models.IntegerField(default=0)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to="rbapp.agency",
                    ),
                ),
                (
                    "bank_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to="rbapp.bankledgerentry",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to="rbapp.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to="rbapp.customerledgerentry",
                    ),
                ),
            ],
        ),
    ]
