# Generated by Django 5.2.4 on 2025-11-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0041_alter_customerledgerentry_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoBankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_batch_id", models.IntegerField(blank=True, null=True)),
                ("operation_date", models.DateField()),
                ("label", models.CharField(max_length=255)),
                ("value_date", models.DateField()),
                ("debit", models.FloatField(blank=True, null=True)),
                ("credit", models.FloatField(blank=True, null=True)),
                (
                    "date_ref",
                    models.DateField(
                        blank=True,
                        help_text="Extracted date reference in YYYY-MM-DD format",
                        null=True,
                    ),
                ),
                ("ref", models.CharField(blank=True, max_length=255, null=True)),
                ("document_reference", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "internal_number",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Transaction type classification",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reco_transactions",
                        to="rbapp.bank",
                    ),
                ),
                (
                    "bank_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reco_transactions",
                        to="rbapp.bankledgerentry",
                    ),
                ),
                (
                    "payment_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rbapp.paymentclass",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoCustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_batch_id", models.IntegerField(blank=True, null=True)),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="N° compte bancaire",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "accounting_date",
                    models.DateField(help_text="Date comptabilisation"),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="N° document", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Description", max_length=255),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Montant débit",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Montant crédit",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "external_doc_number",
                    models.CharField(
                        blank=True,
                        help_text="N° doc. externe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Date d'échéance", null=True
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        help_text="Type de règlement",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Calculated amount (debit - credit)",
                        max_digits=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total amount (absolute value)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "customer_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reco_transactions",
                        to="rbapp.customerledgerentry",
                    ),
                ),
                (
                    "matched_bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked reco bank transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_reco_customer_transactions",
                        to="rbapp.recobanktransaction",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Status from matched bank transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reco_customer_transactions",
                        to="rbapp.paymentstatus",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ReconciliationSession",
        ),
    ]
