# Generated by Django 5.2.4 on 2025-11-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0042_recobanktransaction_recocustomertransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertaxrow",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_rows",
                to="rbapp.recocustomertransaction",
            ),
        ),
    ]
