# Generated by Django 5.2.4 on 2025-11-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0043_alter_customertaxrow_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="customer_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="rbapp.recocustomertransaction",
            ),
        ),
    ]
