# Generated by Django 5.2.4 on 2025-11-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0044_alter_comparison_customer_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="tax",
            unique_together={("name", "company", "bank")},
        ),
    ]
