# Generated by Django 5.2.4 on 2025-11-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0045_alter_tax_name_alter_tax_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="beginning_balance_label",
            field=models.CharField(
                blank=True,
                help_text="Text to search for in the label column to identify beginning balance (e.g., 'SOLDE DEBUT PERIODE')",
                max_length=255,
                null=True,
            ),
        ),
    ]
