# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0048_paymentstatus_accounting_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recobanktransaction",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]






