# Generated by Django 5.2.4 on 2026-01-06 12:29

import rbapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0049_banktransaction_recobanktransaction_accounting_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo image",
                null=True,
                upload_to=rbapp.models.company_logo_upload_path,
            ),
        ),
    ]
