# Generated by Django 5.2.4 on 2026-01-07 10:41

import rbapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0050_add_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Bank logo image",
                null=True,
                upload_to=rbapp.models.bank_logo_upload_path,
            ),
        ),
    ]
