# Generated by Django 5.2.4 on 2026-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbapp", "0051_add_bank_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="difference",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Difference between customer and bank values (customer - bank)",
                max_digits=20,
                null=True,
            ),
        ),
    ]


